version: '3.7'
services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1910
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data: